### ISSUE TITLE
tumbleweed not working

### ISSUE THREAD

**Issue by mybigman** [gsauthof/dracut-sshd#44] opened 2021-03-03 04:00 UTC
Installed on a fresh server install of tumbleweed.

Steps
- Install dracut-sshd
- run dracut -f -v
- reboot

Unable to SSH to machine, ran NMAP scan nothing open.

Alternate steps
- Install dracut-sshd
- use the two configs from example folder on repo
- add additional params to grub
- regenerate grub config
- run dracut -f -v
- reboot

Same response and not seeing any errors in logs :/

**Comment by gsauthof** [comment] 2021-03-05 22:51
One way to debug this is to boot into a dracut-shell (by adding extra kernel command line parameters such as `rd.shell rd.break`) where you could investigate the situation, if you have access to the console. For example, check sshd's status with `systemctl status sshd` etc.

**Comment by DemoFreak** [comment] 2021-05-02 12:31
> Installed on a fresh server install of tumbleweed.

You maybe have to install "systemd-network" (on my fresh Leap 15.3 RC3 machine this package had to be installed manually).

dracut output will show lines like "module not enabled, systemd-networkd.service file not found" (sry, can't remember the exact wording)

**Comment by gsauthof** [comment] 2021-05-15 12:20
Closing this due to not enough information provided. Feel free to reopen it if you have new information or if somebody else can reproduce this.

As is, @DemoFreak 's guess seems the most plausible explanation.

**Closed by gsauthof** 2021-05-15 12:20 UTC
