### ISSUE TITLE
Passphrase not working, although working with normal SSH

### ISSUE THREAD

**Issue by cayolblake** [gsauthof/dracut-sshd#62] opened 2022-10-15 01:11 UTC
@gsauthof I did all the correct procedures, and I verified for ssh auth keys presence through `lsinitrd | grep 'authorized\|bin/sshd\|network/20'` however using my passphrase doesn't work in machine boot, yet works when I normally SSH to the machine after it completely boots.

Fedora 36 64bit with no customization or weird configs whatsoever.

No idea how to debug!

**Comment by gsauthof** [comment] 2022-10-18 22:27
You could unpack the initramfs archive and double check if the central files have the right content.

For further debugging you need console access such that you can interactively start a shell for debugging before you attempt to login into via ssh into the dracut early boot environment. That way you can look into the ssh logs and  the filesystem, live. Perhaps ssh logs some obvious authentication issue then.

If console access is a problem, you can try to reproduce the issue in a VM.

The last question/answer in the FAQ (in the README) has some notes on how to enter such a console shell for debugging.

**Comment by jlsalvador** [comment] 2023-04-29 15:52
Please @cayolblake , can you try with the patch #65 ?

**Comment by gsauthof** [comment] 2023-05-07 17:00
@jlsalvador Since @cayolblake didn't mention any non-standard settings I don't see how your patch would make a difference.

Since Fedora 19, its dracut defaults to `hostonly=yes`.

I'm running dracut-sshd on Fedora 36 and 37 machines with the default hostonly setting and don't see any ssh login issues there.

**Comment by gsauthof** [comment] 2023-06-17 13:41
Closing this, because I can't reproduce it on Fedora 36 til 38.

I just tested a dracut-sshd install via copr on a fresh Fedora 38 system that was installed via the official GUI installer, followed the dracut-sshd readme steps and everything worked as expected.

Feel free to open a new issue if you still have the same issue with recent Fedora/dracut-sshd and can share more   information.

**Closed by gsauthof** 2023-06-17 13:41 UTC
