### ISSUE TITLE
Upgrading Fedora Version does not Work

### ISSUE THREAD

**Issue by laolux** [gsauthof/dracut-sshd#22] opened 2020-04-20 03:37 UTC
Hi, thanks for this great module, it works very great on Fedora 30.
However, when I try to upgrade to Fedora 31 with `dnf system-upgrade reboot`, then I cannot log into my server any more.
One workaround is to boot the server from usb stick after the upgrade, mount the encrypted root filesystem, `chown` to that filesystem and then run `dracut -f -kver [kernelversion]`.
After this procedure I can reboot the server and boot without usb stick assistance.

However, this is quite cumbersome. Does anyone have an idea of how to get `dnf system-upgrade reboot` to automatically execute `dracut -f` before it is done?

**Comment by yellowsquid** [comment] 2020-04-20 09:06
Unfortunately this isn't an issue with this `dracut` module, but with the Fedora package for `dracut` and how it interacts with `dnf`.

It sounds to me that `dnf system-upgrade reboot` doesn't use `dracut` to generate the initramfs and uses some other binary. I do not have a Fedora system so I cannot verify this.

To test this, try the upgrade again. Then from the usb stick, mount the boot partition and run 

```
lsinitrd /path/to/initramfs | grep dracut
```

If you don't get any output then I'm pretty sure that the initramfs image isn't made with dracut.

I'd start by talking for the package maintainer for Fedora to see if they have a `dnf` plugin or hook. If that leads to nowhere then ask the Fedora `dracut` community. If no one else has written one, then you might have to do it yourself.

**Comment by laolux** [comment] 2020-04-21 01:00
Thanks, I had a look at the initramfs after the upgrade.
It uses `dracut` and even includes `sshd`. However, it is missing `systemd-networkd`.
When I regenerate the initramfs when booting from my usb stick, then `systemd-networkd` gets included. So I somehow need to convince `dnf systemd-upgrade reboot` to include `systemd-networkd`. But I guess that question needs to be asked elsewhere.

Here the to part of the output of `lsinitrd` for the original initramfs after upgrade:

    Image: /mnt/initramfs-5.5.16-200.fc31.x86_64.img: 28M                                                          
    ========================================================================                                       
    Version: dracut-050-26.git20200316.fc31                                                                        
                                                                                                                   
    Arguments: -f                                                                                                  
                                                                                                                   
    dracut modules:                                                                                                
    bash                                                                                                           
    systemd                                                                                                        
    systemd-initrd                                                                                                 
    i18n                                                                                                           
    network-manager                                                                                                
    network                                                                                                        
    ifcfg                                                                                                          
    sshd                                                                                                           
    drm                                                                                                            
    plymouth                                                                                                       
    crypt                                                                                                          
    dm                                                                                                             
    kernel-modules                                                                                                 
    kernel-modules-extra                                                                                           
    kernel-network-modules                                                                                         
    qemu                                                                                                           
    qemu-net                                                                                                       
    resume                                                                                                         
    rootfs-block                                                                                                   
    terminfo                                                                                                       
    udev-rules                                                                                                     
    dracut-systemd                                                                                                 
    usrmount                                                                                                       
    base                                                                                                           
    fs-lib                                                                                                         
    shutdown

And here after regenerating with `dracut -f`

    initrd in UEFI: : 30M                                                                                          
    ========================================================================                                       
    Version:                                                                                                       
                                                                                                                   
    Arguments: -f --kver '5.5.16-200.fc31.x86_64'                                                                  
                                                                                                                   
    dracut modules:                                                                                                
    bash                                                                                                           
    systemd                                                                                                        
    systemd-initrd                                                                                                 
    systemd-networkd                                                                                               
    i18n                                                                                                           
    network-manager                                                                                                
    network                                                                                                        
    ifcfg                                                                                                          
    sshd                                                                                                           
    drm                                                                                                            
    plymouth                                                                                                       
    crypt                                                                                                          
    dm                                                                                                             
    kernel-modules                                                                                                 
    kernel-modules-extra                                                                                           
    kernel-network-modules                                                                                         
    qemu                                                                                                           
    qemu-net                                                                                                       
    rootfs-block                                                                                                   
    terminfo                                                                                                       
    udev-rules                                                                                                     
    dracut-systemd                                                                                                 
    usrmount                                                                                                       
    base                                                                                                           
    fs-lib                                                                                                         
    shutdown

**Comment by gsauthof** [comment] 2020-04-27 19:11
Thank you for sharing this information here as this might be helpful for others doing such upgrades.

Personally, I never do Fedora system-upgrades. Instead I install a new Fedora version by executing a disaster recovery playbook that installs Fedora from scratch, automatically installs my package selection, configure everything etc. and then I restore `$HOME` from my backup.

I do this out of an old suspicion that system upgrades aren't as well tested as fresh installs (last but not least because they are inherently more complex than fresh installs).

 I'm closing this issue because this looks like it's caused by another software package.

**Closed by gsauthof** 2020-04-27 19:11 UTC

**Comment by pschmitt** [comment] 2020-06-13 18:18
FYI I just did an upgrade from F31 to 32 and it all worked fine :)
